# @see https://github.com/indiana-university/puppet-aide/blob/master/manifests/init.pp
type Gin::AIDE = Struct[
  {
    Optional['package']                 => String,
    Optional['version']                 => String,
    Optional['conf_path']               => String,
    Optional['db_path']                 => String,
    Optional['db_temp_path']            => String,
    Optional['gzip_dbout']              => Boolean,
    Optional['aide_path']               => String,
    Optional['mail_path']               => String,
    Optional['config_template']         => String,
    Optional['report_ignore_e2fsattrs'] => String,
    Optional['aide_log']                => String,
    Optional['syslogout']               => Boolean,
    Optional['minute']                  => Cron::Minute,
    Optional['hour']                    => Cron::Hour,
    Optional['date']                    => Cron::Date,
    Optional['month']                   => Cron::Month,
    Optional['weekday']                 => Cron::Weekday,
    Optional['exclude_config_argument'] => Boolean,
    Optional['nocheck']                 => Boolean,
    Optional['mailto']                  => String,
    Optional['mail_only_on_changes']    => Boolean,
    Optional['max_mail_lines']          => Integer[1],
    Optional['init_timeout']            => Integer,
    Optional['cat_path']                => String,
    Optional['rm_path']                 => String,
    Optional['head_path']               => String,
  }
]
