# @see https://github.com/puppetlabs/puppetlabs-apt/blob/v7.7.1/manifests/init.pp
type Gin::APT = Struct[
  {
    Optional['apt_conf_d']          => String,
    Optional['auth_conf_entries']   => Array[Apt::Auth_conf_entry],
    Optional['auth_conf_owner']     => String,
    Optional['backports']           => Hash,
    Optional['conf_d']              => String,
    Optional['config_files']        => Hash,
    Optional['confs']               => Hash,
    Optional['include_defaults']    => Hash,
    Optional['key_options']         => String,
    Optional['keys']                => Hash,
    Optional['keyserver']           => String,
    Optional['manage_auth_conf']    => Boolean,
    Optional['pins']                => Hash,
    Optional['ppa_options']         => String,
    Optional['ppa_package']         => String,
    Optional['ppas']                => Hash,
    Optional['preferences']         => String,
    Optional['preferences_d']       => String,
    Optional['provider']            => String,
    Optional['proxy']               => Apt::Proxy,
    Optional['proxy_defaults']      => Hash,
    Optional['purge']               => Hash,
    Optional['purge_defaults']      => Hash,
    Optional['root']                => String,
    Optional['settings']            => Hash,
    Optional['source_key_defaults'] => Hash,
    Optional['sources']             => Hash,
    Optional['sources_list']        => String,
    Optional['sources_list_d']      => String,
    Optional['sources_list_force']  => Boolean,
    Optional['update']              => Hash,
    Optional['update_defaults']     => Hash,
  }
]
