# @see https://puppet.com/docs/puppet/7/types/file.html
type Gin::File = Struct[
  {
    Optional['backup']                  => Boolean,
    Optional['checksum']                => String[1],
    Optional['checksum_value']          => String[1],
    Optional['content']                 => String[1],
    Optional['ctime']                   => Any,
    Optional['ensure']                  => Enum['present', 'absent', 'file', 'directory', 'link'],
    Optional['force']                   => Variant[Boolean, Enum['true', 'false', 'yes', 'no']],
    Optional['group']                   => Variant[Integer, String],
    Optional['ignore']                  => String,
    Optional['links']                   => Enum['follow', 'manage'],
    Optional['max_files']               => Integer,
    Optional['mode']                    => String,
    Optional['mtime']                   => Any,
    Optional['owner']                   => Variant[Integer, String],
    Optional['path']                    => Stdlib::Absolutepath,
    Optional['provider']                => Enum['posix', 'windows'],
    Optional['purge']                   => Variant[Boolean, Enum['true', 'false', 'yes', 'no']],
    Optional['recurse']                 => Variant[Boolean, Enum['false', 'true', 'remote']],
    Optional['recurselimit']            => Integer,
    Optional['replace']                 => Variant[Boolean, Enum['true', 'false', 'yes', 'no']],
    Optional['selinux_ignore_defaults'] => Boolean,
    Optional['selrange']                => Any,
    Optional['selrole']                 => Any,
    Optional['seltype']                 => Any,
    Optional['show_diff']               => Variant[Boolean, Enum['true', 'false', 'yes', 'no']],
    Optional['source']                  => String,
    Optional['source_permissions']      => Enum['use', 'use_when_creating', 'ignore'],
    Optional['sourceselect']            => Enum['first', 'all'],
    Optional['staging_location']        => Any,
    Optional['target']                  => Any,
    Optional['type']                    => Any,
    Optional['validate_cmd']            => Any,
    Optional['validate_replacement']    => Any,
  }
]
